insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (1, 'Skyvu', '300 Sunfield Crossing', 'Albany', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (2, 'Twitterbeat', '965 Pine View Place', 'Chicago', 'Illinois');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (3, 'Youopia', '0348 Meadow Ridge Court', 'Lexington', 'Kentucky');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (4, 'Jabbersphere', '305 Aberg Alley', 'Evansville', 'Indiana');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (5, 'Tekfly', '17 Lakewood Gardens Drive', 'Cincinnati', 'Ohio');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (6, 'Realfire', '29993 Red Cloud Center', 'New Orleans', 'Louisiana');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (7, 'Dazzlesphere', '44625 Starling Drive', 'Houston', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (8, 'Quimm', '0 Marcy Hill', 'South Bend', 'Indiana');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (9, 'Jabbertype', '0 Kenwood Alley', 'Charleston', 'South Carolina');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (10, 'Vimbo', '4 Hayes Hill', 'Burbank', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (11, 'Oyondu', '73168 High Crossing Parkway', 'Fredericksburg', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (12, 'Edgeclub', '44 Ridgeway Court', 'Grand Rapids', 'Michigan');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (13, 'Oyoba', '47 Summerview Pass', 'Toledo', 'Ohio');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (14, 'Fadeo', '43507 Schiller Crossing', 'Dallas', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (15, 'Buzzbean', '1 Michigan Hill', 'San Antonio', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (16, 'Voonte', '5286 Toban Way', 'Lincoln', 'Nebraska');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (17, 'Skyble', '0938 Straubel Crossing', 'Reno', 'Nevada');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (18, 'Wikibox', '053 Gerald Court', 'Green Bay', 'Wisconsin');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (19, 'Miboo', '8553 Bluestem Plaza', 'Fort Myers', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (20, 'Feedbug', '925 Lyons Place', 'Gulfport', 'Mississippi');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (21, 'Rhynyx', '053 Barby Road', 'Roanoke', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (22, 'Youtags', '32087 Eggendart Point', 'Fort Worth', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (23, 'Meejo', '17 Oriole Point', 'Staten Island', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (24, 'Edgeclub', '75477 Browning Way', 'Birmingham', 'Alabama');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (25, 'Skalith', '90 Twin Pines Drive', 'Boise', 'Idaho');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (26, 'Zoovu', '12 Hansons Court', 'Peoria', 'Illinois');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (27, 'Gigashots', '182 Melrose Park', 'Las Vegas', 'Nevada');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (28, 'InnoZ', '280 Chive Way', 'Honolulu', 'Hawaii');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (29, 'Teklist', '02 Di Loreto Terrace', 'Pittsburgh', 'Pennsylvania');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (30, 'Tazzy', '242 Erie Crossing', 'Tulsa', 'Oklahoma');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (31, 'Flipbug', '1 Harbort Plaza', 'Bethesda', 'Maryland');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (32, 'Lazzy', '3 Columbus Street', 'Oakland', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (33, 'Aimbo', '97062 Marcy Way', 'Seattle', 'Washington');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (34, 'Mydo', '720 Sommers Pass', 'Migrate', 'Kentucky');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (35, 'Blogtags', '045 Eastwood Circle', 'Washington', 'District of Columbia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (36, 'Jayo', '83 Melody Plaza', 'Littleton', 'Colorado');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (37, 'Rhynoodle', '292 Cascade Hill', 'Bloomington', 'Illinois');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (38, 'Ozu', '324 Meadow Valley Lane', 'Tulsa', 'Oklahoma');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (39, 'Jabbersphere', '0590 Ohio Parkway', 'Baltimore', 'Maryland');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (40, 'Yoveo', '40 Forest Dale Hill', 'Washington', 'District of Columbia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (41, 'Trupe', '12306 Elgar Parkway', 'Wilmington', 'Delaware');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (42, 'Edgepulse', '05118 Northport Point', 'Albany', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (43, 'Photofeed', '1688 Anzinger Road', 'Roanoke', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (44, 'Browseblab', '546 Monument Park', 'Detroit', 'Michigan');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (45, 'InnoZ', '6018 Summerview Hill', 'Duluth', 'Georgia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (46, 'Twitterworks', '11 La Follette Drive', 'Oklahoma City', 'Oklahoma');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (47, 'Riffpath', '9188 Ramsey Trail', 'Des Moines', 'Iowa');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (48, 'Quatz', '0289 Bellgrove Road', 'Springfield', 'Illinois');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (49, 'Meembee', '41985 Meadow Valley Way', 'Miami', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (50, 'Jazzy', '57 Hauk Way', 'Charlotte', 'North Carolina');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (51, 'Dabjam', '3 Westerfield Court', 'Charlotte', 'North Carolina');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (52, 'Midel', '84271 Pennsylvania Court', 'Richmond', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (53, 'Tazzy', '707 Hoard Point', 'Juneau', 'Alaska');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (54, 'Camimbo', '93886 Jana Road', 'Cincinnati', 'Ohio');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (55, 'Trupe', '360 Village Trail', 'Shreveport', 'Louisiana');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (56, 'Ainyx', '7 Shopko Road', 'Cincinnati', 'Ohio');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (57, 'Divape', '7699 Transport Hill', 'Houston', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (58, 'Centizu', '39 Glacier Hill Center', 'Philadelphia', 'Pennsylvania');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (59, 'Realbridge', '2 Dennis Hill', 'New York City', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (60, 'Minyx', '81 Clove Alley', 'Chicago', 'Illinois');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (61, 'Livetube', '88 Monument Circle', 'New York City', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (62, 'Mynte', '56174 Darwin Point', 'Arlington', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (63, 'Quire', '5737 Pennsylvania Court', 'Pensacola', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (64, 'DabZ', '7 Maple Wood Park', 'Newport Beach', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (65, 'Buzzbean', '79 Bashford Avenue', 'San Antonio', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (66, 'Minyx', '4247 Tomscot Street', 'Baton Rouge', 'Louisiana');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (67, 'Eayo', '495 Sommers Place', 'Albany', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (68, 'Skynoodle', '27125 Mendota Plaza', 'San Antonio', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (69, 'Quire', '105 Mallard Hill', 'Austin', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (70, 'Skyndu', '36 Lakeland Parkway', 'Bradenton', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (71, 'Lazzy', '436 Katie Crossing', 'Richmond', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (72, 'Devbug', '2442 Anthes Lane', 'Roanoke', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (73, 'Aibox', '54 Macpherson Junction', 'Lincoln', 'Nebraska');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (74, 'Skajo', '185 Melby Park', 'Tampa', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (75, 'Wikizz', '400 Meadow Vale Point', 'Washington', 'District of Columbia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (76, 'Rhyloo', '7114 Ridgeway Alley', 'New York City', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (77, 'Photobean', '4316 Manufacturers Way', 'Boston', 'Massachusetts');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (78, 'Youtags', '39036 Manufacturers Plaza', 'El Paso', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (79, 'Jetwire', '102 Mallard Parkway', 'Oklahoma City', 'Oklahoma');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (80, 'Rooxo', '1 Carey Terrace', 'Terre Haute', 'Indiana');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (81, 'Quatz', '764 Miller Hill', 'Chico', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (82, 'Tagtune', '51 Ridgeview Trail', 'Santa Clara', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (83, 'Yakidoo', '21 Straubel Circle', 'Arlington', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (84, 'Zoomcast', '7 Brown Pass', 'Midland', 'Michigan');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (85, 'Katz', '1338 Stuart Crossing', 'Saint Paul', 'Minnesota');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (86, 'Tazz', '84 Eagle Crest Alley', 'Washington', 'District of Columbia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (87, 'Blogtags', '887 International Plaza', 'Oakland', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (88, 'Thoughtblab', '6992 Chinook Junction', 'Philadelphia', 'Pennsylvania');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (89, 'Trilia', '7468 Welch Way', 'Springfield', 'Massachusetts');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (90, 'Riffwire', '143 3rd Center', 'Garland', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (91, 'Yakijo', '79 Elmside Junction', 'Memphis', 'Tennessee');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (92, 'LiveZ', '99941 Bluejay Circle', 'Tacoma', 'Washington');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (93, 'Gabtype', '05116 Corben Way', 'Bethesda', 'Maryland');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (94, 'Skyble', '71 Union Plaza', 'Idaho Falls', 'Idaho');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (95, 'Fivespan', '5 Vidon Point', 'Omaha', 'Nebraska');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (96, 'Oyonder', '8 Homewood Terrace', 'Birmingham', 'Alabama');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (97, 'Eadel', '41869 Forest Dale Pass', 'Wilmington', 'Delaware');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (98, 'Quaxo', '1 Merrick Place', 'Charleston', 'West Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (99, 'Youspan', '9534 Pankratz Court', 'Memphis', 'Tennessee');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (100, 'Feednation', '9140 Lindbergh Way', 'Atlanta', 'Georgia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (101, 'Trunyx', '13879 Evergreen Pass', 'Omaha', 'Nebraska');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (102, 'Shuffletag', '49 Forest Dale Junction', 'Sacramento', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (103, 'Meevee', '36 Beilfuss Drive', 'Boston', 'Massachusetts');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (104, 'Yacero', '09 Petterle Plaza', 'Carlsbad', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (105, 'Jazzy', '0674 Maple Wood Road', 'San Bernardino', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (106, 'Browsezoom', '6883 Glendale Drive', 'Madison', 'Wisconsin');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (107, 'Trudeo', '2 Gateway Crossing', 'Boise', 'Idaho');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (108, 'Oba', '02 Straubel Terrace', 'North Las Vegas', 'Nevada');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (109, 'Zoomlounge', '473 Heffernan Park', 'Humble', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (110, 'Zoovu', '5997 Del Sol Lane', 'Monticello', 'Minnesota');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (111, 'Gevee', '442 Loftsgordon Place', 'Bellevue', 'Washington');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (112, 'Zooveo', '7 Welch Road', 'Spokane', 'Washington');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (113, 'Divape', '23197 Kedzie Circle', 'Washington', 'District of Columbia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (114, 'Dabshots', '230 Melby Point', 'Chicago', 'Illinois');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (115, 'Skalith', '0 Kedzie Crossing', 'San Francisco', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (116, 'Centidel', '7782 Dapin Junction', 'Philadelphia', 'Pennsylvania');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (117, 'Twimm', '2 Summer Ridge Pass', 'Fargo', 'North Dakota');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (118, 'Browsezoom', '77163 Comanche Avenue', 'Saint Petersburg', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (119, 'Agimba', '04 Arapahoe Park', 'Dallas', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (120, 'Jabberstorm', '88580 Fairfield Lane', 'Birmingham', 'Alabama');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (121, 'Vinder', '4 Memorial Place', 'Lubbock', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (122, 'Trupe', '650 Rockefeller Crossing', 'Milwaukee', 'Wisconsin');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (123, 'Quaxo', '71 La Follette Junction', 'Youngstown', 'Ohio');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (124, 'Gigabox', '6431 Veith Lane', 'Asheville', 'North Carolina');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (125, 'Thoughtsphere', '17 Kim Trail', 'Muncie', 'Indiana');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (126, 'Ainyx', '79 Westend Point', 'Cincinnati', 'Ohio');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (127, 'Lazzy', '15 Carey Crossing', 'Muncie', 'Indiana');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (128, 'Livetube', '197 Luster Junction', 'El Paso', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (129, 'Roomm', '2 Sugar Junction', 'Mobile', 'Alabama');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (130, 'Rhyloo', '38356 Utah Place', 'Wichita Falls', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (131, 'Minyx', '5612 Melvin Lane', 'Littleton', 'Colorado');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (132, 'Twinte', '4163 Debra Avenue', 'Davenport', 'Iowa');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (133, 'Trudeo', '5730 Farragut Hill', 'Richmond', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (134, 'Roodel', '91 Prentice Terrace', 'North Hollywood', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (135, 'Mydo', '1 Express Place', 'San Jose', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (136, 'Trudeo', '1763 Gulseth Terrace', 'Panama City', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (137, 'Twinder', '75763 Stoughton Trail', 'Hot Springs National Park', 'Arkansas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (138, 'Twitterworks', '947 Gulseth Avenue', 'El Paso', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (139, 'Eadel', '06730 Goodland Road', 'Denver', 'Colorado');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (140, 'Mycat', '50578 Thompson Way', 'East Saint Louis', 'Illinois');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (141, 'Yodel', '9 Service Way', 'Charlotte', 'North Carolina');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (142, 'Voolia', '403 Meadow Vale Plaza', 'Corpus Christi', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (143, 'Jaxbean', '9493 Warrior Circle', 'Los Angeles', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (144, 'Jazzy', '8 Walton Street', 'Pittsburgh', 'Pennsylvania');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (145, 'Tambee', '5090 Vahlen Circle', 'Greenville', 'South Carolina');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (146, 'Realfire', '9076 Manufacturers Alley', 'Miami', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (147, 'Kazu', '66 Lindbergh Terrace', 'Orlando', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (148, 'Topicshots', '1306 Vahlen Place', 'Oklahoma City', 'Oklahoma');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (149, 'Topicware', '73899 Magdeline Point', 'Richmond', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (150, 'Skaboo', '4113 Forest Circle', 'Raleigh', 'North Carolina');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (151, 'Babblestorm', '286 1st Trail', 'Richmond', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (152, 'Dabtype', '5855 Sunnyside Place', 'Tulsa', 'Oklahoma');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (153, 'Twimbo', '7805 Service Parkway', 'Pittsburgh', 'Pennsylvania');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (154, 'Gigabox', '5551 Hovde Road', 'Killeen', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (155, 'Realmix', '341 Buena Vista Drive', 'Kansas City', 'Missouri');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (156, 'Devpulse', '9 Cascade Trail', 'Paterson', 'New Jersey');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (157, 'Skippad', '05 Elgar Court', 'Dallas', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (158, 'Feedspan', '9 Parkside Trail', 'Reston', 'Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (159, 'Omba', '61 Lotheville Trail', 'Wichita', 'Kansas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (160, 'Buzzdog', '95691 Duke Road', 'Shawnee Mission', 'Kansas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (161, 'Youspan', '3 Warbler Point', 'Rochester', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (162, 'Zoombeat', '4 Portage Way', 'Fort Wayne', 'Indiana');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (163, 'Tazzy', '800 Forest Parkway', 'San Francisco', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (164, 'Twitternation', '3 Haas Avenue', 'Silver Spring', 'Maryland');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (165, 'Snaptags', '466 Manley Park', 'Fresno', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (166, 'Flashdog', '78 Stoughton Point', 'Irvine', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (167, 'Gigaclub', '967 Morning Alley', 'Albany', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (168, 'Twiyo', '421 Gale Park', 'Abilene', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (169, 'Topicstorm', '6054 Fuller Terrace', 'New York City', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (170, 'Ainyx', '435 Bay Crossing', 'Santa Ana', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (171, 'Voonix', '2978 Coolidge Point', 'Salt Lake City', 'Utah');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (172, 'Fanoodle', '32 Jenifer Way', 'El Paso', 'Texas');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (173, 'Thoughtblab', '1055 Mccormick Road', 'Santa Ana', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (174, 'Photobean', '225 Lyons Crossing', 'Macon', 'Georgia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (175, 'Thoughtbridge', '2464 Ruskin Point', 'Charleston', 'West Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (176, 'Edgewire', '45818 Pierstorff Plaza', 'Boynton Beach', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (177, 'Quinu', '2219 Tomscot Hill', 'Monticello', 'Minnesota');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (178, 'Kaymbo', '43213 Coleman Point', 'Bradenton', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (179, 'Yoveo', '09778 Vahlen Center', 'Portland', 'Oregon');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (180, 'Photofeed', '52028 Hintze Lane', 'Los Angeles', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (181, 'Roodel', '80559 Forest Dale Crossing', 'Seattle', 'Washington');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (182, 'Twimbo', '6149 Oakridge Drive', 'Rochester', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (183, 'Flipbug', '8 Becker Center', 'Bloomington', 'Illinois');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (184, 'Zooxo', '7831 Becker Pass', 'Asheville', 'North Carolina');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (185, 'Brainlounge', '84 Maple Crossing', 'Bradenton', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (186, 'Zoombeat', '284 Lyons Hill', 'Missoula', 'Montana');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (187, 'Realbridge', '3 Shasta Lane', 'Berkeley', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (188, 'Fivechat', '3107 Surrey Place', 'Madison', 'Wisconsin');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (189, 'Photospace', '896 Bowman Terrace', 'Sacramento', 'California');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (190, 'Brainlounge', '545 Saint Paul Parkway', 'Oklahoma City', 'Oklahoma');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (191, 'Skyndu', '84 Gale Trail', 'Atlanta', 'Georgia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (192, 'Babbleblab', '517 Holmberg Crossing', 'Jamaica', 'New York');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (193, 'Midel', '35076 School Lane', 'Beaverton', 'Oregon');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (194, 'Twitterwire', '2361 Northfield Terrace', 'Naples', 'Florida');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (195, 'Bluejam', '03 Blackbird Avenue', 'Charleston', 'West Virginia');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (196, 'Tagchat', '1172 Hintze Hill', 'Scottsdale', 'Arizona');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (197, 'Topicblab', '7 Ronald Regan Court', 'Woburn', 'Massachusetts');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (198, 'Oyoyo', '5564 Ridge Oak Pass', 'Monticello', 'Minnesota');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (199, 'Zoomzone', '76888 David Alley', 'Dayton', 'Ohio');
insert into Loja (id_loja, nome_loja, rua, cidade, distrito) values (200, 'Vinte', '98302 Morrow Plaza', 'Dallas', 'Texas');
