insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (1, 'Realcube', 2001, 'Médiamass', 'Lakeland', 'Milwaukee', 'Wisconsin');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (2, 'Livepath', 1995, 'Wá', 'Weeping Birch', 'Spokane', 'Washington');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (3, 'Thoughtbridge', 2003, 'Irène', 'Thackeray', 'El Paso', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (4, 'Ntag', 2012, 'Eléonore', 'Crescent Oaks', 'Houston', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (5, 'Ainyx', 2020, 'Cunégonde', 'Glacier Hill', 'Nashville', 'Tennessee');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (6, 'Jabberstorm', 2001, 'Styrbjörn', 'Oak Valley', 'Savannah', 'Georgia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (7, 'Bubbletube', 2005, 'Eloïse', 'Warner', 'Danbury', 'Connecticut');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (8, 'Zazio', 1991, 'Célestine', 'Bunting', 'Herndon', 'Virginia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (9, 'Oyondu', 2020, 'Marie-françoise', 'Hovde', 'Des Moines', 'Iowa');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (10, 'Snaptags', 1994, 'Mélys', 'Lotheville', 'Greenville', 'South Carolina');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (11, 'Meembee', 2012, 'Tú', 'Hoepker', 'Denver', 'Colorado');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (12, 'Fatz', 1990, 'Gaétane', 'Blackbird', 'Nashville', 'Tennessee');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (13, 'Kwilith', 2004, 'Océane', 'Green', 'San Jose', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (14, 'Dabjam', 1994, 'Andréa', 'Quincy', 'Charlotte', 'North Carolina');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (15, 'Brightbean', 2009, 'Dorothée', 'Florence', 'Brooklyn', 'New York');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (16, 'Devify', 2002, 'Judicaël', 'Spohn', 'Topeka', 'Kansas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (17, 'Viva', 2015, 'Cléa', 'Redwing', 'Albany', 'Georgia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (18, 'Geba', 2017, 'Célestine', 'Holy Cross', 'Idaho Falls', 'Idaho');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (19, 'Flashspan', 1999, 'Kévina', 'Union', 'Albany', 'New York');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (20, 'Pixoboo', 2013, 'Ráo', 'Thompson', 'San Diego', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (21, 'Gevee', 2001, 'Dù', 'Magdeline', 'Toledo', 'Ohio');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (22, 'Abatz', 1999, 'Maëlle', 'Melrose', 'Lynchburg', 'Virginia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (23, 'Brainbox', 1997, 'Léane', 'Claremont', 'Marietta', 'Georgia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (24, 'Feedspan', 2020, 'Méthode', 'Atwood', 'Pensacola', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (25, 'Yamia', 2012, 'Célia', 'Marquette', 'Birmingham', 'Alabama');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (26, 'Twimbo', 1996, 'Lén', 'Hovde', 'Peoria', 'Illinois');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (27, 'Feedfish', 2018, 'Maëly', 'Mariners Cove', 'Saint Cloud', 'Minnesota');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (28, 'Mybuzz', 2020, 'Personnalisée', 'Leroy', 'Ocala', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (29, 'Quinu', 2007, 'Cécile', 'Norway Maple', 'Fort Lauderdale', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (30, 'Yoveo', 1998, 'Aurélie', 'Pond', 'Irving', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (31, 'Photobug', 2016, 'Aí', 'Vahlen', 'Charlotte', 'North Carolina');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (32, 'Skynoodle', 2008, 'Eléa', 'Mifflin', 'Hot Springs National Park', 'Arkansas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (33, 'Izio', 1998, 'Yú', 'Erie', 'Kansas City', 'Missouri');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (34, 'Oyoyo', 2016, 'Hélèna', 'Straubel', 'Glendale', 'Arizona');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (35, 'Babbleopia', 2005, 'Stévina', 'Annamark', 'Glendale', 'Arizona');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (36, 'Shufflebeat', 2007, 'Måns', 'Mcbride', 'North Little Rock', 'Arkansas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (37, 'Miboo', 2005, 'Méthode', 'School', 'Washington', 'District of Columbia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (38, 'Yacero', 1992, 'Régine', 'Little Fleur', 'Dallas', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (39, 'Meeveo', 1990, 'Médiamass', 'Maple Wood', 'El Paso', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (40, 'Mynte', 2020, 'Françoise', 'Valley Edge', 'Sacramento', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (41, 'Quamba', 2016, 'Maïlys', 'Scott', 'Washington', 'District of Columbia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (42, 'Topicstorm', 1996, 'Lèi', 'Arkansas', 'Dallas', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (43, 'Minyx', 2003, 'Béatrice', 'Florence', 'Detroit', 'Michigan');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (44, 'Mydo', 2013, 'Andrée', 'Onsgard', 'Dallas', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (45, 'Demivee', 2005, 'Irène', 'Erie', 'Naples', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (46, 'Mydeo', 2013, 'Zhì', 'Lakewood Gardens', 'Dallas', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (47, 'Devify', 2016, 'Gérald', 'Hagan', 'Olympia', 'Washington');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (48, 'Jaxspan', 2017, 'Ruò', 'Surrey', 'Loretto', 'Minnesota');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (49, 'Browsezoom', 2009, 'Maïwenn', 'Loftsgordon', 'Metairie', 'Louisiana');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (50, 'Youspan', 2013, 'Stévina', 'Nobel', 'Washington', 'District of Columbia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (51, 'Voonder', 2009, 'Mylène', 'Johnson', 'Huntsville', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (52, 'Mymm', 2005, 'Loïc', 'Kings', 'Bethesda', 'Maryland');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (53, 'Riffpath', 1996, 'Salomé', 'Larry', 'Phoenix', 'Arizona');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (54, 'Skaboo', 2002, 'Bérengère', 'Texas', 'Seattle', 'Washington');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (55, 'Pixope', 2018, 'Ruò', 'Burning Wood', 'Trenton', 'New Jersey');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (56, 'Fliptune', 2013, 'Cléa', 'Golf Course', 'Pittsburgh', 'Pennsylvania');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (57, 'Omba', 1997, 'Styrbjörn', 'Kensington', 'Albany', 'New York');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (58, 'Zoovu', 2017, 'Estève', 'Pine View', 'Lakeland', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (59, 'Dabtype', 1991, 'Táng', 'Grim', 'Wichita', 'Kansas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (60, 'Youtags', 2011, 'Wá', 'Springview', 'Escondido', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (61, 'Skyble', 1998, 'Océane', 'Ruskin', 'Austin', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (62, 'Oba', 1994, 'Lauréna', 'Brentwood', 'Shawnee Mission', 'Kansas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (63, 'Zoombox', 1995, 'Stéphanie', 'Basil', 'New York City', 'New York');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (64, 'DabZ', 2015, 'Françoise', 'Harper', 'Chicago', 'Illinois');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (65, 'Skivee', 2002, 'Clélia', 'Express', 'Houston', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (66, 'Oyoba', 1998, 'Naëlle', 'Ohio', 'Fort Smith', 'Arkansas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (67, 'Vipe', 2009, 'Cécile', '4th', 'Washington', 'District of Columbia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (68, 'Twitterbridge', 1996, 'Célia', 'Saint Paul', 'Houston', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (69, 'Wikivu', 2009, 'Mylène', 'Artisan', 'Austin', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (70, 'Twimbo', 2004, 'Eliès', 'Northwestern', 'New York City', 'New York');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (71, 'Avaveo', 2001, 'Mélanie', 'Bashford', 'Houston', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (72, 'Vidoo', 2020, 'Dafnée', 'West', 'Jackson', 'Mississippi');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (73, 'Livetube', 2004, 'Maïwenn', 'Bashford', 'Santa Clara', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (74, 'Devify', 1993, 'Yóu', 'Gale', 'El Paso', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (75, 'Babblestorm', 2019, 'Léana', 'Lunder', 'Wilmington', 'Delaware');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (76, 'Vinte', 1990, 'Françoise', 'Hollow Ridge', 'Washington', 'District of Columbia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (77, 'Trilith', 2015, 'Mélia', 'Spenser', 'Shawnee Mission', 'Kansas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (78, 'Fadeo', 2007, 'Maéna', 'Boyd', 'Orange', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (79, 'Aivee', 1998, 'Maëlla', 'Spohn', 'Salt Lake City', 'Utah');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (80, 'Ozu', 2017, 'Kuí', 'Acker', 'Houston', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (81, 'Devify', 1991, 'Méline', 'Washington', 'Sterling', 'Virginia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (82, 'Thoughtsphere', 2013, 'Liè', 'Hoepker', 'Fort Wayne', 'Indiana');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (83, 'Eamia', 1998, 'Estève', 'Rowland', 'Philadelphia', 'Pennsylvania');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (84, 'Devcast', 2015, 'André', 'Vernon', 'Jackson', 'Mississippi');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (85, 'Fiveclub', 2004, 'Néhémie', 'Green Ridge', 'Tampa', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (86, 'Zoombeat', 2020, 'Ráo', 'Sugar', 'Bronx', 'New York');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (87, 'Kwideo', 2011, 'Mårten', 'Lien', 'Lubbock', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (88, 'Yoveo', 1992, 'Angélique', 'Claremont', 'Bethesda', 'Maryland');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (89, 'Buzzster', 2003, 'Kù', 'Service', 'Saint Louis', 'Missouri');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (90, 'Buzzbean', 2001, 'Dorothée', 'Basil', 'Denver', 'Colorado');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (91, 'Youtags', 1993, 'Maïlis', 'Hoepker', 'San Jose', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (92, 'Mudo', 2016, 'Kuí', 'Vernon', 'Sioux Falls', 'South Dakota');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (93, 'Voonte', 2004, 'Bénédicte', 'Tennyson', 'San Jose', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (94, 'Mybuzz', 2017, 'Cléopatre', 'Lotheville', 'Pensacola', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (95, 'Yata', 2019, 'Mélina', 'Thackeray', 'Des Moines', 'Iowa');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (96, 'Skiba', 2000, 'Clélia', 'Hayes', 'Chula Vista', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (97, 'Skynoodle', 2019, 'Gaétane', 'Luster', 'Philadelphia', 'Pennsylvania');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (98, 'Riffwire', 2014, 'Hélène', 'Bellgrove', 'Bozeman', 'Montana');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (99, 'Minyx', 2009, 'Solène', 'Reindahl', 'Evansville', 'Indiana');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (100, 'Dynazzy', 2011, 'Alizée', 'Columbus', 'Waterloo', 'Iowa');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (101, 'Voonix', 2015, 'Lorène', 'Dottie', 'Schenectady', 'New York');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (102, 'Ntag', 1996, 'Hélèna', 'Upham', 'Newton', 'Massachusetts');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (103, 'Avaveo', 2012, 'Bécassine', 'Utah', 'Irvine', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (104, 'Kwinu', 2017, 'André', 'Burrows', 'New Orleans', 'Louisiana');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (105, 'Kwimbee', 2001, 'Eugénie', 'Troy', 'San Jose', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (106, 'Leexo', 2001, 'Tú', 'Magdeline', 'Washington', 'District of Columbia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (107, 'Blogpad', 2005, 'Åke', 'Oriole', 'Waterbury', 'Connecticut');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (108, 'Eidel', 2003, 'Valérie', 'Manufacturers', 'Mobile', 'Alabama');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (109, 'Centizu', 2010, 'Océanne', 'Sullivan', 'Davenport', 'Iowa');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (110, 'Photospace', 2018, 'Irène', 'Vidon', 'Mesa', 'Arizona');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (111, 'Jaxbean', 1999, 'Mahélie', 'Merrick', 'Stockton', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (112, 'Feedspan', 2006, 'Maëly', 'Pierstorff', 'Monticello', 'Minnesota');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (113, 'Zoovu', 2015, 'Almérinda', 'Debs', 'Sacramento', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (114, 'Brightdog', 2011, 'Adélaïde', 'Oneill', 'Cleveland', 'Ohio');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (115, 'Avamm', 1995, 'Miléna', 'Lindbergh', 'Lexington', 'Kentucky');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (116, 'Twitterlist', 2012, 'Yè', 'Sloan', 'Palmdale', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (117, 'Einti', 1994, 'Gaïa', 'Crescent Oaks', 'Portsmouth', 'New Hampshire');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (118, 'Youopia', 2007, 'Médiamass', 'Dwight', 'Albany', 'Georgia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (119, 'Kwideo', 1995, 'Jú', 'Gina', 'Fort Wayne', 'Indiana');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (120, 'Gabvine', 2014, 'Cléa', 'Sachs', 'Washington', 'District of Columbia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (121, 'Zooveo', 2001, 'Måns', 'Kingsford', 'Dallas', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (122, 'Layo', 2010, 'Tán', 'Claremont', 'Omaha', 'Nebraska');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (123, 'Fliptune', 2006, 'Eléa', 'Lakeland', 'Albuquerque', 'New Mexico');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (124, 'Oyonder', 1994, 'Gaëlle', 'Messerschmidt', 'Fort Lauderdale', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (125, 'Skyble', 2006, 'Jú', 'Pepper Wood', 'Minneapolis', 'Minnesota');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (126, 'Geba', 2011, 'Kallisté', 'Onsgard', 'Philadelphia', 'Pennsylvania');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (127, 'Meejo', 1999, 'Yénora', 'Waywood', 'Houston', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (128, 'Voonix', 2015, 'Yè', 'Maple', 'Carol Stream', 'Illinois');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (129, 'Oloo', 2010, 'Cléopatre', 'Elka', 'Washington', 'District of Columbia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (130, 'Realpoint', 2019, 'Annotée', '5th', 'North Port', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (131, 'Realfire', 2000, 'Illustrée', '6th', 'Honolulu', 'Hawaii');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (132, 'Topicblab', 1997, 'Méthode', 'Scofield', 'Flint', 'Michigan');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (133, 'Ntag', 1996, 'Célia', 'Laurel', 'Minneapolis', 'Minnesota');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (134, 'Midel', 2020, 'Maëlle', 'Jay', 'Daytona Beach', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (135, 'Ozu', 1999, 'Erwéi', 'Buell', 'Syracuse', 'New York');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (136, 'Eazzy', 2002, 'Börje', 'Golf', 'Evansville', 'Indiana');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (137, 'Ntag', 2003, 'Daphnée', 'American', 'Ogden', 'Utah');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (138, 'Fivespan', 2009, 'Lyséa', 'Doe Crossing', 'Roanoke', 'Virginia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (139, 'Vitz', 1999, 'Alizée', 'Mayfield', 'Gulfport', 'Mississippi');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (140, 'Aivee', 2013, 'Mélodie', 'Milwaukee', 'Las Vegas', 'Nevada');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (141, 'Fanoodle', 2018, 'Béatrice', 'Butternut', 'Macon', 'Georgia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (142, 'Lazz', 2012, 'Léonore', 'Fordem', 'Lincoln', 'Nebraska');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (143, 'Voonder', 1994, 'Görel', 'Spaight', 'Jefferson City', 'Missouri');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (144, 'Skalith', 2002, 'Kallisté', 'Orin', 'Detroit', 'Michigan');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (145, 'Camido', 2019, 'Göran', 'Manitowish', 'Monticello', 'Minnesota');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (146, 'Cogibox', 2017, 'Magdalène', 'Cascade', 'Albuquerque', 'New Mexico');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (147, 'Flashdog', 2020, 'Frédérique', 'Golf View', 'Amarillo', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (148, 'Wikivu', 2009, 'Lèi', 'Schmedeman', 'Los Angeles', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (149, 'Voolia', 2004, 'Mélodie', 'Lake View', 'Des Moines', 'Iowa');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (150, 'Skippad', 2004, 'Cunégonde', 'Prairie Rose', 'Columbus', 'Ohio');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (151, 'Feedmix', 2016, 'Méline', 'Bluejay', 'Richmond', 'Virginia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (152, 'Meezzy', 2011, 'Gaïa', 'Porter', 'Littleton', 'Colorado');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (153, 'Realmix', 1990, 'Amélie', 'Sullivan', 'Vienna', 'Virginia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (154, 'Wordtune', 1993, 'Tán', 'Loeprich', 'Des Moines', 'Iowa');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (155, 'Meetz', 1999, 'Maëlys', 'Longview', 'Madison', 'Wisconsin');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (156, 'Buzzdog', 2004, 'Maëlyss', 'Dakota', 'Fresno', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (157, 'Quatz', 1994, 'Géraldine', 'Oak Valley', 'Portland', 'Maine');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (158, 'Dabshots', 1998, 'Yè', 'Tennyson', 'Seattle', 'Washington');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (159, 'Wikizz', 2004, 'Béatrice', 'Clarendon', 'Temple', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (160, 'Topiclounge', 2010, 'Zhì', 'Westerfield', 'San Diego', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (161, 'Bubblemix', 2002, 'Athéna', 'Lake View', 'Memphis', 'Tennessee');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (162, 'Mymm', 2007, 'Anaé', 'High Crossing', 'Washington', 'District of Columbia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (163, 'Tazz', 2009, 'Vérane', 'Beilfuss', 'Whittier', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (164, 'Jaxbean', 2006, 'Léonore', 'Pearson', 'Escondido', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (165, 'Oyondu', 2010, 'Alizée', 'Weeping Birch', 'Tampa', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (166, 'Jaxbean', 1991, 'Marylène', 'Sunbrook', 'Seattle', 'Washington');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (167, 'Zoomzone', 2003, 'Annotés', 'Hoffman', 'Mobile', 'Alabama');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (168, 'Tambee', 1994, 'Pélagie', 'Vidon', 'Saint Paul', 'Minnesota');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (169, 'Topicshots', 2005, 'Åsa', 'Petterle', 'Bakersfield', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (170, 'Yodoo', 2011, 'Mylène', 'Artisan', 'High Point', 'North Carolina');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (171, 'Dabjam', 1994, 'Intéressant', 'Kropf', 'Amarillo', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (172, 'Devbug', 1997, 'Uò', 'Laurel', 'Pittsburgh', 'Pennsylvania');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (173, 'Geba', 1995, 'Gisèle', 'Farwell', 'Rockville', 'Maryland');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (174, 'Tagtune', 2013, 'Angélique', 'Dennis', 'Philadelphia', 'Pennsylvania');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (175, 'Meeveo', 2001, 'Océane', 'Independence', 'Whittier', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (176, 'Lazzy', 2019, 'Ophélie', 'Porter', 'Charleston', 'West Virginia');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (177, 'Ailane', 2006, 'Göran', 'Michigan', 'Fort Collins', 'Colorado');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (178, 'Cogilith', 1991, 'Célia', 'Stang', 'Lakeland', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (179, 'Thoughtsphere', 2020, 'Anaël', 'Loomis', 'Santa Barbara', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (180, 'Realpoint', 2012, 'Lyséa', 'Redwing', 'San Antonio', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (181, 'Zoombox', 1994, 'Marie-hélène', 'Farmco', 'Pittsburgh', 'Pennsylvania');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (182, 'Wikizz', 1999, 'Illustrée', 'Haas', 'Fresno', 'California');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (183, 'Meejo', 2009, 'Mélia', 'Walton', 'Denver', 'Colorado');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (184, 'Talane', 2000, 'Tú', 'Oakridge', 'Dallas', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (185, 'Jetpulse', 2019, 'Thérèsa', 'Grover', 'Tulsa', 'Oklahoma');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (186, 'Skipstorm', 2009, 'Gaétane', 'Merchant', 'Springfield', 'Ohio');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (187, 'Meezzy', 2014, 'Andréa', 'Canary', 'Vero Beach', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (188, 'Yombu', 1993, 'Maïly', 'Carey', 'Memphis', 'Tennessee');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (189, 'Devpoint', 2002, 'Uò', 'Hanover', 'Honolulu', 'Hawaii');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (190, 'Wordify', 1993, 'Anaïs', 'Tennyson', 'Houston', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (191, 'Mynte', 1993, 'Angèle', 'Buell', 'Chandler', 'Arizona');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (192, 'Kanoodle', 2020, 'Thérèsa', 'Chive', 'Indianapolis', 'Indiana');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (193, 'Twitterbridge', 2005, 'Loïc', 'Forest Dale', 'Birmingham', 'Alabama');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (194, 'Skyndu', 1993, 'Michèle', 'Stuart', 'Clearwater', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (195, 'Shuffletag', 1993, 'Laurène', 'Golf View', 'Tampa', 'Florida');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (196, 'Innojam', 2019, 'Styrbjörn', 'Sheridan', 'Wilkes Barre', 'Pennsylvania');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (197, 'Jabberbean', 1992, 'Sòng', 'Chive', 'Detroit', 'Michigan');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (198, 'Realcube', 2009, 'Cunégonde', 'Lillian', 'Houston', 'Texas');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (199, 'Aimbu', 1994, 'Uò', 'Fuller', 'Mobile', 'Alabama');
insert into cinema (id_cinema, designacao, ano_abertura, gerente, rua, cidade, distrito) values (200, 'Wordpedia', 2011, 'Desirée', 'Hovde', 'Spokane', 'Washington');
