insert into concessao (id_concessao, tipoitem, precounitario) values (1, 'Tamarind Paste', 11);
insert into concessao (id_concessao, tipoitem, precounitario) values (2, 'Chicken - Diced, Cooked', 18);
insert into concessao (id_concessao, tipoitem, precounitario) values (3, 'Chicken - Soup Base', 18);
insert into concessao (id_concessao, tipoitem, precounitario) values (4, 'Island Oasis - Lemonade', 18);
insert into concessao (id_concessao, tipoitem, precounitario) values (5, 'Alize Red Passion', 17);
insert into concessao (id_concessao, tipoitem, precounitario) values (6, 'Beer - Steamwhistle', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (7, 'Pasta - Fusili, Dry', 4);
insert into concessao (id_concessao, tipoitem, precounitario) values (8, 'Wine - Manischewitz Concord', 25);
insert into concessao (id_concessao, tipoitem, precounitario) values (9, 'Table Cloth 62x120 Colour', 6);
insert into concessao (id_concessao, tipoitem, precounitario) values (10, 'Foil Wrap', 17);
insert into concessao (id_concessao, tipoitem, precounitario) values (11, 'Lychee - Canned', 22);
insert into concessao (id_concessao, tipoitem, precounitario) values (12, 'Fond - Chocolate', 21);
insert into concessao (id_concessao, tipoitem, precounitario) values (13, 'Marzipan 50/50', 25);
insert into concessao (id_concessao, tipoitem, precounitario) values (14, 'Sprouts - Brussel', 25);
insert into concessao (id_concessao, tipoitem, precounitario) values (15, 'Marzipan 50/50', 17);
insert into concessao (id_concessao, tipoitem, precounitario) values (16, 'Yucca', 14);
insert into concessao (id_concessao, tipoitem, precounitario) values (17, 'Tomatoes - Roma', 8);
insert into concessao (id_concessao, tipoitem, precounitario) values (18, 'Soup - Verve - Chipotle Chicken', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (19, 'Wine - Blue Nun Qualitatswein', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (20, 'Puree - Blackcurrant', 4);
insert into concessao (id_concessao, tipoitem, precounitario) values (21, 'Coffee - Ristretto Coffee Capsule', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (22, 'Pasta - Fettuccine, Egg, Fresh', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (23, 'Table Cloth - 53x69 Colour', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (24, 'Lamb Leg - Bone - In Nz', 15);
insert into concessao (id_concessao, tipoitem, precounitario) values (25, 'Tomatoes - Yellow Hot House', 19);
insert into concessao (id_concessao, tipoitem, precounitario) values (26, 'Clams - Bay', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (27, 'Baking Powder', 22);
insert into concessao (id_concessao, tipoitem, precounitario) values (28, 'Mangostein', 25);
insert into concessao (id_concessao, tipoitem, precounitario) values (29, 'Sauce - Fish 25 Ozf Bottle', 8);
insert into concessao (id_concessao, tipoitem, precounitario) values (30, 'Container - Foam Dixie 12 Oz', 13);
insert into concessao (id_concessao, tipoitem, precounitario) values (31, 'Bar Nature Valley', 14);
insert into concessao (id_concessao, tipoitem, precounitario) values (32, 'Rum - Cream, Amarula', 24);
insert into concessao (id_concessao, tipoitem, precounitario) values (33, 'Cheese - Valancey', 17);
insert into concessao (id_concessao, tipoitem, precounitario) values (34, 'Soup - Knorr, French Onion', 24);
insert into concessao (id_concessao, tipoitem, precounitario) values (35, 'Miso Paste White', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (36, 'Salsify, Organic', 6);
insert into concessao (id_concessao, tipoitem, precounitario) values (37, 'Icecream - Dstk Cml And Fdg', 9);
insert into concessao (id_concessao, tipoitem, precounitario) values (38, 'Ham Black Forest', 19);
insert into concessao (id_concessao, tipoitem, precounitario) values (39, 'Mountain Dew', 25);
insert into concessao (id_concessao, tipoitem, precounitario) values (40, 'Asparagus - Mexican', 10);
insert into concessao (id_concessao, tipoitem, precounitario) values (41, 'Jolt Cola - Electric Blue', 3);
insert into concessao (id_concessao, tipoitem, precounitario) values (42, 'Beef - Short Ribs', 21);
insert into concessao (id_concessao, tipoitem, precounitario) values (43, 'Onions - White', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (44, 'Pea - Snow', 18);
insert into concessao (id_concessao, tipoitem, precounitario) values (45, 'Drambuie', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (46, 'Orange Roughy 4/6 Oz', 14);
insert into concessao (id_concessao, tipoitem, precounitario) values (47, 'Crab - Claws, Snow 16 - 24', 13);
insert into concessao (id_concessao, tipoitem, precounitario) values (48, 'Pears - Bosc', 16);
insert into concessao (id_concessao, tipoitem, precounitario) values (49, 'Bar Mix - Pina Colada, 355 Ml', 19);
insert into concessao (id_concessao, tipoitem, precounitario) values (50, 'Soup Knorr Chili With Beans', 9);
insert into concessao (id_concessao, tipoitem, precounitario) values (51, 'Wine - Beaujolais Villages', 22);
insert into concessao (id_concessao, tipoitem, precounitario) values (52, 'Salt And Pepper Mix - Black', 25);
insert into concessao (id_concessao, tipoitem, precounitario) values (53, 'Nestea - Ice Tea, Diet', 6);
insert into concessao (id_concessao, tipoitem, precounitario) values (54, 'Bread - Raisin Walnut Pull', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (55, 'Cheese - Swiss Sliced', 20);
insert into concessao (id_concessao, tipoitem, precounitario) values (56, 'Soup - Campbells Asian Noodle', 24);
insert into concessao (id_concessao, tipoitem, precounitario) values (57, 'Baking Powder', 25);
insert into concessao (id_concessao, tipoitem, precounitario) values (58, 'Nantucket - Carrot Orange', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (59, 'Muffin Orange Individual', 14);
insert into concessao (id_concessao, tipoitem, precounitario) values (60, 'Wine - Chardonnay South', 9);
insert into concessao (id_concessao, tipoitem, precounitario) values (61, 'Tomatoes - Hot House', 6);
insert into concessao (id_concessao, tipoitem, precounitario) values (62, 'Bread - English Muffin', 16);
insert into concessao (id_concessao, tipoitem, precounitario) values (63, 'Lettuce - Romaine, Heart', 5);
insert into concessao (id_concessao, tipoitem, precounitario) values (64, 'Quail Eggs - Canned', 11);
insert into concessao (id_concessao, tipoitem, precounitario) values (65, 'Pecan Raisin - Tarts', 6);
insert into concessao (id_concessao, tipoitem, precounitario) values (66, 'Rice - Basmati', 14);
insert into concessao (id_concessao, tipoitem, precounitario) values (67, 'Beef - Ox Tongue', 4);
insert into concessao (id_concessao, tipoitem, precounitario) values (68, 'Hipnotiq Liquor', 24);
insert into concessao (id_concessao, tipoitem, precounitario) values (69, 'Juice - V8, Tomato', 22);
insert into concessao (id_concessao, tipoitem, precounitario) values (70, 'Wine - Chateauneuf Du Pape', 5);
insert into concessao (id_concessao, tipoitem, precounitario) values (71, 'Alize Sunset', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (72, 'Dill Weed - Fresh', 14);
insert into concessao (id_concessao, tipoitem, precounitario) values (73, 'Rice - 7 Grain Blend', 1);
insert into concessao (id_concessao, tipoitem, precounitario) values (74, 'Basil - Pesto Sauce', 15);
insert into concessao (id_concessao, tipoitem, precounitario) values (75, 'Tamarillo', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (76, 'Tuna - Yellowfin', 9);
insert into concessao (id_concessao, tipoitem, precounitario) values (77, 'Wine - Vouvray Cuvee Domaine', 10);
insert into concessao (id_concessao, tipoitem, precounitario) values (78, 'Cup Translucent 9 Oz', 19);
insert into concessao (id_concessao, tipoitem, precounitario) values (79, 'Yogurt - Blueberry, 175 Gr', 24);
insert into concessao (id_concessao, tipoitem, precounitario) values (80, 'Nori Sea Weed - Gold Label', 9);
insert into concessao (id_concessao, tipoitem, precounitario) values (81, 'Lamb - Loin Chops', 3);
insert into concessao (id_concessao, tipoitem, precounitario) values (82, 'Milk - Chocolate 250 Ml', 8);
insert into concessao (id_concessao, tipoitem, precounitario) values (83, 'Transfer Sheets', 24);
insert into concessao (id_concessao, tipoitem, precounitario) values (84, 'Wine - Pinot Noir Latour', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (85, 'Cheese - Woolwich Goat, Log', 17);
insert into concessao (id_concessao, tipoitem, precounitario) values (86, 'Dried Peach', 3);
insert into concessao (id_concessao, tipoitem, precounitario) values (87, 'External Supplier', 12);
insert into concessao (id_concessao, tipoitem, precounitario) values (88, 'Magnotta - Bel Paese White', 12);
insert into concessao (id_concessao, tipoitem, precounitario) values (89, 'Beans - Kidney, Canned', 14);
insert into concessao (id_concessao, tipoitem, precounitario) values (90, 'Dooleys Toffee', 3);
insert into concessao (id_concessao, tipoitem, precounitario) values (91, 'Whmis - Spray Bottle Trigger', 21);
insert into concessao (id_concessao, tipoitem, precounitario) values (92, 'Green Tea Refresher', 13);
insert into concessao (id_concessao, tipoitem, precounitario) values (93, 'Pasta - Elbows, Macaroni, Dry', 5);
insert into concessao (id_concessao, tipoitem, precounitario) values (94, 'Pasta - Fusili Tri - Coloured', 18);
insert into concessao (id_concessao, tipoitem, precounitario) values (95, 'Pasta - Linguini, Dry', 17);
insert into concessao (id_concessao, tipoitem, precounitario) values (96, 'Muffin Mix - Chocolate Chip', 20);
insert into concessao (id_concessao, tipoitem, precounitario) values (97, 'Roe - White Fish', 6);
insert into concessao (id_concessao, tipoitem, precounitario) values (98, 'Coffee - Irish Cream', 16);
insert into concessao (id_concessao, tipoitem, precounitario) values (99, 'Cleaner - Pine Sol', 17);
insert into concessao (id_concessao, tipoitem, precounitario) values (100, 'Ecolab - Ster Bac', 25);
insert into concessao (id_concessao, tipoitem, precounitario) values (101, 'Nantucket Pine Orangebanana', 24);
insert into concessao (id_concessao, tipoitem, precounitario) values (102, 'Milkettes - 2%', 16);
insert into concessao (id_concessao, tipoitem, precounitario) values (103, 'Spoon - Soup, Plastic', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (104, 'Liners - Banana, Paper', 7);
insert into concessao (id_concessao, tipoitem, precounitario) values (105, 'Pork - Chop, Frenched', 9);
insert into concessao (id_concessao, tipoitem, precounitario) values (106, 'Cleaner - Comet', 21);
insert into concessao (id_concessao, tipoitem, precounitario) values (107, 'Yogurt - Assorted Pack', 13);
insert into concessao (id_concessao, tipoitem, precounitario) values (108, 'Beef Flat Iron Steak', 7);
insert into concessao (id_concessao, tipoitem, precounitario) values (109, 'Bananas', 24);
insert into concessao (id_concessao, tipoitem, precounitario) values (110, 'Puree - Guava', 6);
insert into concessao (id_concessao, tipoitem, precounitario) values (111, 'Chocolate Bar - Smarties', 7);
insert into concessao (id_concessao, tipoitem, precounitario) values (112, 'Veal - Kidney', 8);
insert into concessao (id_concessao, tipoitem, precounitario) values (113, 'Beans - Long, Chinese', 9);
insert into concessao (id_concessao, tipoitem, precounitario) values (114, 'Five Alive Citrus', 3);
insert into concessao (id_concessao, tipoitem, precounitario) values (115, 'Ice Cream - Super Sandwich', 14);
insert into concessao (id_concessao, tipoitem, precounitario) values (116, 'Tomatoes - Heirloom', 14);
insert into concessao (id_concessao, tipoitem, precounitario) values (117, 'Lemonade - Natural, 591 Ml', 5);
insert into concessao (id_concessao, tipoitem, precounitario) values (118, 'Chocolate - Dark', 25);
insert into concessao (id_concessao, tipoitem, precounitario) values (119, 'Island Oasis - Sweet And Sour Mix', 5);
insert into concessao (id_concessao, tipoitem, precounitario) values (120, 'Wine - Prosecco Valdobiaddene', 19);
insert into concessao (id_concessao, tipoitem, precounitario) values (121, 'Food Colouring - Green', 12);
insert into concessao (id_concessao, tipoitem, precounitario) values (122, 'Cheese Cheddar Processed', 12);
insert into concessao (id_concessao, tipoitem, precounitario) values (123, 'Compound - Orange', 1);
insert into concessao (id_concessao, tipoitem, precounitario) values (124, 'Calypso - Strawberry Lemonade', 13);
insert into concessao (id_concessao, tipoitem, precounitario) values (125, 'Table Cloth - 53x69 Colour', 16);
insert into concessao (id_concessao, tipoitem, precounitario) values (126, 'Bag Stand', 10);
insert into concessao (id_concessao, tipoitem, precounitario) values (127, 'Red Cod Fillets - 225g', 15);
insert into concessao (id_concessao, tipoitem, precounitario) values (128, 'Vaccum Bag - 14x20', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (129, 'Bread - Rye', 4);
insert into concessao (id_concessao, tipoitem, precounitario) values (130, 'Caviar - Salmon', 18);
insert into concessao (id_concessao, tipoitem, precounitario) values (131, 'Icecream Bar - Del Monte', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (132, 'Bonito Flakes - Toku Katsuo', 15);
insert into concessao (id_concessao, tipoitem, precounitario) values (133, 'Tuna - Loin', 20);
insert into concessao (id_concessao, tipoitem, precounitario) values (134, 'Creme De Cacao White', 12);
insert into concessao (id_concessao, tipoitem, precounitario) values (135, 'Flour - Teff', 14);
insert into concessao (id_concessao, tipoitem, precounitario) values (136, 'Nut - Cashews, Whole, Raw', 15);
insert into concessao (id_concessao, tipoitem, precounitario) values (137, 'Mayonnaise', 5);
insert into concessao (id_concessao, tipoitem, precounitario) values (138, 'Tart - Pecan Butter Squares', 11);
insert into concessao (id_concessao, tipoitem, precounitario) values (139, 'Wine - Ice Wine', 1);
insert into concessao (id_concessao, tipoitem, precounitario) values (140, 'Cheese - Brie Roitelet', 16);
insert into concessao (id_concessao, tipoitem, precounitario) values (141, 'Bagels Poppyseed', 14);
insert into concessao (id_concessao, tipoitem, precounitario) values (142, 'Soup - Campbells, Classic Chix', 3);
insert into concessao (id_concessao, tipoitem, precounitario) values (143, 'Bread - French Stick', 7);
insert into concessao (id_concessao, tipoitem, precounitario) values (144, 'Asparagus - Mexican', 12);
insert into concessao (id_concessao, tipoitem, precounitario) values (145, 'Truffle Cups - Red', 21);
insert into concessao (id_concessao, tipoitem, precounitario) values (146, 'Noodles - Cellophane, Thin', 7);
insert into concessao (id_concessao, tipoitem, precounitario) values (147, 'Clams - Canned', 21);
insert into concessao (id_concessao, tipoitem, precounitario) values (148, 'Strawberries - California', 15);
insert into concessao (id_concessao, tipoitem, precounitario) values (149, 'Cranberries - Fresh', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (150, 'Sausage - Blood Pudding', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (151, 'Fiddlehead - Frozen', 11);
insert into concessao (id_concessao, tipoitem, precounitario) values (152, 'Wiberg Cure', 4);
insert into concessao (id_concessao, tipoitem, precounitario) values (153, 'Cleaner - Bleach', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (154, 'Marjoram - Fresh', 4);
insert into concessao (id_concessao, tipoitem, precounitario) values (155, 'Ecolab - Ster Bac', 18);
insert into concessao (id_concessao, tipoitem, precounitario) values (156, 'Mcguinness - Blue Curacao', 18);
insert into concessao (id_concessao, tipoitem, precounitario) values (157, 'Pears - Fiorelle', 12);
insert into concessao (id_concessao, tipoitem, precounitario) values (158, 'Gatorade - Lemon Lime', 25);
insert into concessao (id_concessao, tipoitem, precounitario) values (159, 'Tray - 16in Rnd Blk', 18);
insert into concessao (id_concessao, tipoitem, precounitario) values (160, 'Steampan - Foil', 4);
insert into concessao (id_concessao, tipoitem, precounitario) values (161, 'Soup - Knorr, French Onion', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (162, 'Cheese - Goat With Herbs', 19);
insert into concessao (id_concessao, tipoitem, precounitario) values (163, 'Sauce - Apple, Unsweetened', 15);
insert into concessao (id_concessao, tipoitem, precounitario) values (164, 'Extract - Almond', 12);
insert into concessao (id_concessao, tipoitem, precounitario) values (165, 'Soup - Base Broth Beef', 22);
insert into concessao (id_concessao, tipoitem, precounitario) values (166, 'Pepper - Red Bell', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (167, 'Wine - Cahors Ac 2000, Clos', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (168, 'Bread - Rosemary Focaccia', 22);
insert into concessao (id_concessao, tipoitem, precounitario) values (169, 'Wine - Niagara,vqa Reisling', 24);
insert into concessao (id_concessao, tipoitem, precounitario) values (170, 'Sauce - Gravy, Au Jus, Mix', 20);
insert into concessao (id_concessao, tipoitem, precounitario) values (171, 'Soup - Base Broth Beef', 5);
insert into concessao (id_concessao, tipoitem, precounitario) values (172, 'Table Cloth 53x69 White', 25);
insert into concessao (id_concessao, tipoitem, precounitario) values (173, 'Soup - Canadian Pea, Dry Mix', 13);
insert into concessao (id_concessao, tipoitem, precounitario) values (174, 'Jello - Assorted', 1);
insert into concessao (id_concessao, tipoitem, precounitario) values (175, 'Soup - Knorr, Veg / Beef', 5);
insert into concessao (id_concessao, tipoitem, precounitario) values (176, 'Rice - Long Grain', 6);
insert into concessao (id_concessao, tipoitem, precounitario) values (177, 'Chocolate - Feathers', 8);
insert into concessao (id_concessao, tipoitem, precounitario) values (178, 'Turkey - Breast, Bone - In', 1);
insert into concessao (id_concessao, tipoitem, precounitario) values (179, 'Chocolate - Pistoles, White', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (180, 'Ham - Cooked', 15);
insert into concessao (id_concessao, tipoitem, precounitario) values (181, 'Flour - Corn, Fine', 18);
insert into concessao (id_concessao, tipoitem, precounitario) values (182, 'Otomegusa Dashi Konbu', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (183, 'Fish - Scallops, Cold Smoked', 13);
insert into concessao (id_concessao, tipoitem, precounitario) values (184, 'Bread - Burger', 16);
insert into concessao (id_concessao, tipoitem, precounitario) values (185, 'Turnip - White, Organic', 23);
insert into concessao (id_concessao, tipoitem, precounitario) values (186, 'Danishes - Mini Cheese', 6);
insert into concessao (id_concessao, tipoitem, precounitario) values (187, 'Sauce - Mint', 2);
insert into concessao (id_concessao, tipoitem, precounitario) values (188, 'Dried Apple', 7);
insert into concessao (id_concessao, tipoitem, precounitario) values (189, 'Soy Protein', 1);
insert into concessao (id_concessao, tipoitem, precounitario) values (190, 'Cornflakes', 4);
insert into concessao (id_concessao, tipoitem, precounitario) values (191, 'Wasabi Paste', 10);
insert into concessao (id_concessao, tipoitem, precounitario) values (192, 'Wine - Niagara Peninsula Vqa', 13);
insert into concessao (id_concessao, tipoitem, precounitario) values (193, 'Soup - Chicken And Wild Rice', 19);
insert into concessao (id_concessao, tipoitem, precounitario) values (194, 'Pasta - Fettuccine, Egg, Fresh', 10);
insert into concessao (id_concessao, tipoitem, precounitario) values (195, 'Cookies - Fortune', 1);
insert into concessao (id_concessao, tipoitem, precounitario) values (196, 'Cookies Oatmeal Raisin', 7);
insert into concessao (id_concessao, tipoitem, precounitario) values (197, 'Veal - Loin', 22);
insert into concessao (id_concessao, tipoitem, precounitario) values (198, 'Carbonated Water - Wildberry', 21);
insert into concessao (id_concessao, tipoitem, precounitario) values (199, 'Gloves - Goldtouch Disposable', 16);
insert into concessao (id_concessao, tipoitem, precounitario) values (200, 'Pheasants - Whole', 25);
