insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (1, 'Kukuli', 'Drama', 99, 'Clare');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (2, 'Five People You Meet in Heaven, The', 'Drama|Fantasy', 205, 'Aldin');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (3, 'Zero', 'Drama', 285, 'Valentino');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (4, 'Stealing a Nation', 'Documentary', 316, 'Emanuel');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (5, 'Circle of Deception, A', 'Drama|War', 306, 'Abdul');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (6, 'The Hearts of Age', '(no genres listed)', 136, 'Cristobal');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (7, 'Ladies in Retirement', 'Drama', 280, 'Jared');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (8, 'Collision Earth', 'Action|Sci-Fi', 105, 'Rudolph');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (9, 'Company of Wolves, The', 'Fantasy|Horror', 81, 'Winny');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (10, 'Attenberg', 'Drama', 150, 'Adair');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (11, 'Fire Birds', 'Action|Adventure', 95, 'Wiley');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (12, 'Oleanna', 'Drama', 343, 'Osbert');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (13, 'King in New York, A', 'Comedy|Drama', 114, 'Fabien');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (14, 'Killer: A Journal of Murder', 'Crime|Drama', 194, 'Bax');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (15, 'Guess Who', 'Comedy|Romance', 281, 'Zacharie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (16, 'Prince and the Pauper, The', 'Adventure|Drama', 146, 'Edan');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (17, 'Shine a Light', 'Documentary|Musical|IMAX', 228, 'Vincent');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (18, 'Wave, The (Welle, Die)', 'Drama', 305, 'Edmund');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (19, 'You Will Meet a Tall Dark Stranger', 'Comedy|Romance', 265, 'Benoit');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (20, '1066', 'Action|Adventure|War', 260, 'Tailor');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (21, '3 Sailors and a Girl (Three Sailors and a Girl)', 'Comedy|Musical', 235, 'Budd');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (22, 'Russia''s Toughest Prisons (National Geographic)', 'Documentary', 221, 'Monro');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (23, 'Attack!', 'Drama|War', 271, 'Kimball');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (24, 'Sphinx', 'Mystery|Thriller', 145, 'Antin');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (25, 'Return of the Vampire, The', 'Horror', 308, 'Nickolas');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (26, 'Godzilla Raids Again (Gojira no gyakushû)', 'Action|Drama|Horror|Romance|Sci-Fi', 235, 'Myer');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (27, 'Family Honeymoon', 'Comedy|Romance', 80, 'Bartlet');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (28, 'T-Men', 'Film-Noir', 313, 'Odie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (29, 'Escape From Tomorrow', 'Drama|Fantasy|Horror', 68, 'Lemmie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (30, 'Son of Babylon (Syn Babilonu)', 'Drama', 210, 'Tymon');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (31, 'Abandoned, The', 'Horror|Mystery|Thriller', 250, 'Tam');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (32, 'Space', 'Drama', 263, 'Carmine');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (33, 'Miss Representation', 'Documentary', 204, 'Bondon');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (34, 'Kids for Cash', 'Documentary|Thriller', 303, 'Alexandre');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (35, 'Mirror, The (Zerkalo)', 'Drama', 309, 'Vasili');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (36, 'Africa Screams', 'Adventure|Comedy', 80, 'Richmound');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (37, 'Room 666 (Chambre 666)', 'Documentary', 94, 'Dael');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (38, 'Phantom of the Rue Morgue', 'Crime|Horror|Mystery', 69, 'Garey');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (39, 'Revenge of the Green Dragons', 'Action|Crime|Drama', 317, 'Benito');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (40, 'Hustler White', 'Romance', 65, 'Clyde');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (41, 'Brother (Hermano)', 'Drama', 78, 'Lindon');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (42, 'Invitation to Happiness', 'Drama|Romance', 174, 'Merle');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (43, 'Half Light', 'Romance|Thriller', 154, 'Dimitri');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (44, 'Tiresia', 'Drama', 134, 'Carmine');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (45, 'Greatest, The', 'Drama|Romance', 315, 'Benson');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (46, 'Halloween 4: The Return of Michael Myers', 'Horror', 243, 'Benn');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (47, 'Logan''s Run', 'Action|Adventure|Sci-Fi', 82, 'Sunny');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (48, 'C.S.A.: The Confederate States of America', 'Comedy|Drama', 144, 'Kalil');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (49, 'Proud Valley, The', 'Drama', 117, 'Falito');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (50, 'Appropriate Adult', 'Drama', 340, 'Thorny');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (51, 'Kiss Me (Kyss Mig)', 'Drama|Romance', 214, 'Martie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (52, 'Escape From Tomorrow', 'Drama|Fantasy|Horror', 161, 'Michal');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (53, 'Swann in Love (Un amour de Swann)', 'Drama', 100, 'Yanaton');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (54, 'Hard to Hold', 'Drama|Romance', 181, 'Read');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (55, 'Let the Fire Burn', 'Documentary', 322, 'Stu');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (56, 'Still Breathing', 'Comedy|Romance', 108, 'Delaney');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (57, 'French Fried Vacation 2 (Les bronzés font du ski)', 'Comedy', 251, 'Mallory');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (58, 'Pascali''s Island', 'Drama', 242, 'Sayers');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (59, 'A Good Marriage', 'Thriller', 191, 'Titus');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (60, 'Little Nicky', 'Comedy', 222, 'Kingston');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (61, 'Dreams on Spec', 'Documentary', 261, 'Kermit');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (62, 'Weight of the Nation', 'Documentary', 232, 'El');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (63, 'Once Upon a Time in the West (C''era una volta il West)', 'Action|Drama|Western', 237, 'Dolf');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (64, 'Never Sleep Again: The Elm Street Legacy', 'Documentary', 228, 'Parke');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (65, 'Soldier''s Story, A', 'Drama', 343, 'Cullie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (66, 'Six by Sondheim', 'Documentary', 272, 'Anders');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (67, 'Detective Story', 'Crime|Drama|Film-Noir', 174, 'Guthry');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (68, 'Pay or Die', 'Crime', 169, 'Lewes');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (69, 'xXx', 'Action|Crime|Thriller', 94, 'Georgi');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (70, 'Yesterday Girl (Abschied von gestern - Anita G.)', 'Comedy|Romance', 250, 'Bondy');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (71, 'My Perestroika', 'Documentary', 330, 'Walsh');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (72, 'Moving Out', 'Drama', 339, 'Willis');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (73, 'All Night Long', 'Comedy|Drama', 234, 'Woodie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (74, 'House IV', 'Fantasy|Horror|Thriller', 200, 'Xerxes');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (75, 'Lilting', 'Drama', 226, 'Graham');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (76, 'Things to Do in Denver When You''re Dead', 'Crime|Drama|Romance', 178, 'Munroe');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (77, 'Kazaam', 'Children|Comedy|Fantasy', 259, 'Denys');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (78, 'Mega Piranha', 'Action|Adventure|Horror|Sci-Fi', 272, 'Esteban');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (79, 'Behind the Sun (Abril Despedaçado)', 'Drama', 211, 'Dougie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (80, 'Fiddle-de-dee', 'Animation|Musical', 106, 'Terrell');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (81, 'The Kingdom of Dreams and Madness', 'Animation|Documentary', 321, 'Dionysus');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (82, 'Triad Underworld (Gong wu) (Jiang Hu)', 'Action|Crime|Drama', 310, 'Frank');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (83, 'The Good Lie', 'Drama', 110, 'Thebault');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (84, 'Twin Dragons (Shuang long hui)', 'Action|Comedy', 234, 'Bearnard');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (85, 'Crimetime', 'Thriller', 79, 'Garth');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (86, 'Love the Beast', 'Documentary', 234, 'Gaspard');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (87, 'NeverEnding Story II: The Next Chapter, The', 'Adventure|Children|Fantasy', 283, 'Jonathan');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (88, 'Like Mike', 'Children|Comedy|Fantasy', 239, 'Burtie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (89, 'Love and a Bullet', 'Action|Crime', 183, 'Gordie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (90, 'Last Exit to Brooklyn', 'Drama', 289, 'Jamaal');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (91, 'My Mom Is a Character (Minha Mãe é uma Peça: O Filme)', 'Comedy', 201, 'Burnaby');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (92, 'Nowhere', 'Comedy|Drama', 78, 'Angel');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (93, 'Somebody Up There Likes Me', 'Action|Crime|Drama', 268, 'Archie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (94, 'Christmas Story, A', 'Children|Comedy', 187, 'Aguistin');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (95, 'Mars Needs Moms', 'Action|Adventure|Animation|Children|Comedy|Sci-Fi|IMAX', 186, 'Jeff');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (96, 'Messengers, The', 'Drama|Horror|Thriller', 111, 'Esme');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (97, 'Visiting Hours', 'Horror', 91, 'Warner');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (98, 'Iran Job, The', 'Documentary', 252, 'Malcolm');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (99, 'Dunwich Horror, The', 'Horror', 169, 'Farlay');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (100, 'Lucky Them', 'Drama', 313, 'Hillier');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (101, 'No Regrets for Our Youth (Waga seishun ni kuinashi)', 'Drama', 144, 'Merrel');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (102, 'Hitchhiker''s Guide to the Galaxy, The', 'Adventure|Comedy|Sci-Fi', 270, 'Edvard');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (103, 'The Eagle and the Hawk', 'Action|Drama|War', 218, 'Matt');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (104, 'Ivanhoe', 'Adventure|Drama|Romance', 350, 'Mackenzie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (105, 'Man from the Future, The (O Homem do Futuro)', 'Comedy|Fantasy|Sci-Fi', 94, 'Morton');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (106, 'Cemetery Man (Dellamorte Dellamore)', 'Horror', 345, 'Martino');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (107, 'Ambush (Rukajärven tie)', 'Drama|Romance|War', 143, 'Wain');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (108, 'Presence, The', 'Drama|Horror|Thriller', 355, 'Ken');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (109, 'Grown Up Movie Star', 'Drama', 319, 'Arni');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (110, '''Hellboy'': The Seeds of Creation', 'Action|Adventure|Comedy|Documentary|Fantasy', 308, 'Avrom');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (111, 'Great Directors', 'Documentary', 335, 'Barrie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (112, 'Roxanne', 'Comedy|Romance', 214, 'Sly');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (113, 'Party Monster', 'Comedy|Crime|Drama|Thriller', 334, 'Griffy');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (114, 'God is Great, I''m Not (Dieu est grand, je suis toute petite)', 'Comedy|Romance', 172, 'Cirillo');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (115, 'Harry Potter and the Sorcerer''s Stone (a.k.a. Harry Potter and the Philosopher''s Stone)', 'Adventure|Children|Fantasy', 90, 'Stewart');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (116, 'Nighthawks', 'Action|Drama', 260, 'Araldo');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (117, 'Telling You', 'Comedy|Drama|Romance', 345, 'Raimund');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (118, 'Sun on the Horizon', 'Documentary', 334, 'Benji');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (119, 'Living Free', 'Adventure|Children|Drama', 290, 'Flinn');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (120, 'Julia''s Eyes (Ojos de Julia, Los)', 'Horror|Thriller', 216, 'Herrick');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (121, 'Wrong Turn at Tahoe', 'Action|Crime|Thriller', 186, 'Kippy');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (122, 'Charlie Bartlett', 'Comedy|Drama', 77, 'Jase');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (123, 'External Affairs', 'Drama', 357, 'Rich');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (124, 'Pancho, the Millionaire Dog', 'Children|Comedy', 324, 'Richardo');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (125, 'Monty Python''s The Meaning of Life', 'Comedy', 235, 'Sonny');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (126, 'Flawless', 'Crime|Drama', 300, 'Adam');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (127, 'Bettie Page Reveals All', 'Documentary', 114, 'Darryl');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (128, 'Lost Patrol, The', 'Adventure|Drama|War', 187, 'Kayne');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (129, 'Ice Age Columbus: Who Were the First Americans?', 'Documentary', 124, 'Antonin');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (130, 'Proof of Life', 'Drama', 63, 'Torin');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (131, 'Remember the Day', 'Drama|Romance|War', 103, 'Padgett');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (132, 'Undertaking Betty (Plots with a View)', 'Comedy|Romance', 318, 'Hewet');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (133, 'Mysteries of Pittsburgh, The', 'Adventure|Comedy|Drama', 239, 'Tomas');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (134, 'Roots', 'Drama|War', 285, 'Bowie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (135, 'Obvious Child', 'Comedy|Romance', 255, 'Humphrey');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (136, 'Whisper', 'Crime|Drama|Horror|Thriller', 175, 'Eberto');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (137, 'Cherry 2000', 'Romance|Sci-Fi', 278, 'Shurwood');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (138, 'Mortician, The', 'Thriller', 358, 'Elias');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (139, 'Storm in Summer, A', 'Drama', 144, 'Ethelred');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (140, 'Day Night Day Night', 'Crime|Drama|Thriller', 229, 'Alden');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (141, 'Accidental Husband, The', 'Comedy|Romance', 257, 'Gris');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (142, 'Much Ado About Nothing', 'Comedy|Romance', 265, 'Abdel');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (143, 'Notorious C.H.O.', 'Comedy', 279, 'Conant');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (144, 'Gone', 'Drama|Thriller', 200, 'Shepperd');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (145, 'Two Men in Manhattan (Deux hommes dans Manhattan)', 'Crime|Drama|Thriller', 180, 'Sander');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (146, 'Raintree County', 'Drama|Romance', 307, 'Nolan');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (147, 'Meet Wally Sparks', 'Comedy', 350, 'Dionysus');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (148, 'General, The', 'Comedy|War', 126, 'Antoine');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (149, 'Fancy Pants', 'Comedy|Western', 273, 'Jarad');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (150, 'Miehen tie', 'Drama', 341, 'Emmerich');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (151, 'Hart of London, The', 'Drama', 243, 'Akim');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (152, 'Pirates! Band of Misfits, The', 'Adventure|Animation|Children|Comedy', 323, 'Travus');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (153, 'Brothers O''Toole, The', 'Comedy|Western', 180, 'Earlie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (154, 'Doubt', 'Drama|Mystery', 228, 'Verge');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (155, 'Hotel Pacific (Zaklete rewiry)', 'Drama', 198, 'Sully');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (156, 'Austin High', 'Comedy', 179, 'Ross');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (157, 'Hood of the Living Dead', 'Horror', 204, 'Leland');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (158, 'Dragonheart 3: The Sorcerer''s Curse', 'Action|Adventure|Fantasy', 342, 'Jackson');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (159, 'Haunted Strangler, The (Grip of the Strangler)', 'Crime|Horror|Mystery', 246, 'Amery');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (160, 'Cliffhanger', 'Action|Adventure|Thriller', 263, 'Elbert');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (161, 'Lili''s Apron', 'Comedy', 347, 'Sanders');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (162, 'Black Rock', 'Horror|Thriller', 182, 'Edik');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (163, 'High School Hellcats', 'Crime|Drama', 164, 'Daron');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (164, 'Flightplan', 'Action|Drama|Thriller', 65, 'Remington');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (165, 'Mr. Holland''s Opus', 'Drama', 309, 'Ole');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (166, 'Mask of Dimitrios, The', 'Crime|Drama|Film-Noir|Mystery', 227, 'Reg');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (167, 'All This, and Heaven Too', 'Drama|Romance', 286, 'Merrick');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (168, 'Frankenstein Conquers the World', 'Action|Drama|Sci-Fi', 208, 'Bennie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (169, 'The Golden Cage', 'Drama', 281, 'Grover');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (170, 'Fill the Void (Lemale et ha''halal)', 'Drama', 78, 'Lothario');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (171, 'Resident, The', 'Drama|Horror|Thriller', 114, 'Wallie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (172, '12 Rounds', 'Action|Thriller', 216, 'Reece');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (173, 'Then She Found Me', 'Comedy|Drama|Romance', 271, 'Clare');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (174, 'Little Manhattan', 'Children|Comedy|Romance', 193, 'Morrie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (175, 'Dead Men Walk', 'Drama|Horror|Mystery', 281, 'Shayne');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (176, 'First Case, Second Case (Ghazieh-e Shekl-e Aval, Ghazieh-e Shekl-e Dou Wom)', 'Documentary', 267, 'Shannon');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (177, 'American Outlaws', 'Action|Comedy|Western', 282, 'Job');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (178, 'In Time', 'Crime|Sci-Fi|Thriller', 97, 'Tyson');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (179, 'Hellsinki (Rööperi)', 'Crime', 143, 'Octavius');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (180, 'Dead, The', 'Drama', 82, 'Darnell');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (181, 'The Land Before Time XII: The Great Day of the Flyers', 'Animation|Children|Sci-Fi', 341, 'Jackson');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (182, 'Who Do I Gotta Kill?', 'Comedy', 91, 'Sal');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (183, 'Psycho', 'Crime|Horror|Thriller', 69, 'Gearard');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (184, 'Terra (a.k.a. Battle for Terra)', 'Adventure|Animation|Sci-Fi', 342, 'Douglas');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (185, 'Star Maker, The (Uomo delle stelle, L'')', 'Drama', 216, 'Consalve');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (186, 'Punk Singer, The', 'Documentary', 357, 'Adam');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (187, 'Tonight and Every Night', 'Musical', 126, 'Richard');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (188, 'Trail Beyond, The', 'Action|Adventure|Western', 128, 'Clay');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (189, 'Big Bad Love', 'Drama', 201, 'Ruddie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (190, 'Garden State', 'Comedy|Drama|Romance', 344, 'Torrence');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (191, 'Licence to Kill', 'Action|Adventure|Thriller', 282, 'Buddie');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (192, 'Defiance', 'Action|Crime|Drama', 261, 'Grantham');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (193, 'The Way He Looks', 'Drama|Romance', 233, 'Bil');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (194, 'White Lightning', 'Action|Crime|Drama', 168, 'Dru');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (195, 'EMR', 'Thriller', 320, 'Giraud');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (196, 'Hello Ladies: The Movie', 'Comedy', 325, 'Zed');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (197, 'Lucky Number Slevin', 'Crime|Drama|Mystery', 342, 'Sherm');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (198, 'Atomic Cafe, The', 'Documentary|War', 277, 'Bondy');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (199, 'Three Crowns of the Sailor (Les trois couronnes du matelot)', 'Drama|Fantasy', 123, 'Julius');
insert into filme (id_filme, titulo, genero, duracao_min, diretor) values (200, 'I Accuse', 'Crime|Drama|Thriller', 130, 'Aluin');
