insert into funcionario (id_funcionario, nome, tipo) values (1, 'Joby Ramme', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (2, 'Cherilynn McCahill', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (3, 'Corie Hacket', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (4, 'Goldina Aubrun', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (5, 'Leanora Ainsbury', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (6, 'Jeno Fridd', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (7, 'Yance Linay', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (8, 'Constantino Balcers', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (9, 'Jeramey Treadway', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (10, 'Ferdy Orneles', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (11, 'Pavel Simonian', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (12, 'Ania Kolinsky', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (13, 'Matthew Tickel', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (14, 'Borg Okenfold', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (15, 'Leandra Pammenter', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (16, 'Mercie Thunder', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (17, 'Daryl Rearden', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (18, 'Leigh Silley', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (19, 'Perry Garnam', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (20, 'Addia Fullager', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (21, 'Elyse Goroni', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (22, 'Ethyl Whartonby', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (23, 'Margret Askell', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (24, 'Alysia Kempton', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (25, 'Ignace Seaward', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (26, 'Lorene Flett', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (27, 'Leontine Vigars', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (28, 'Wendie Edworthie', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (29, 'Kirbie Crebbin', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (30, 'Micheil Trowell', 'Research and Development');
insert into funcionario (id_funcionario, nome, tipo) values (31, 'Gifford Readman', 'Research and Development');
insert into funcionario (id_funcionario, nome, tipo) values (32, 'Javier Featherstonehaugh', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (33, 'Aarika Ziemsen', 'Research and Development');
insert into funcionario (id_funcionario, nome, tipo) values (34, 'Mark Bickerstaffe', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (35, 'Dario Bagott', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (36, 'Donnell McGettrick', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (37, 'Burr Swires', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (38, 'Merilee Rippingale', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (39, 'Lilias Blumsom', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (40, 'Brooks Wavell', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (41, 'Vin MacLise', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (42, 'Dionis Kisby', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (43, 'Otis Tofpik', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (44, 'Ana Thurlbeck', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (45, 'Aldis Rapi', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (46, 'Lolly Aartsen', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (47, 'Nerta Geffcock', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (48, 'Brent Maciejewski', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (49, 'Donni Caunce', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (50, 'Neill Helling', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (51, 'Bertram Drinan', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (52, 'Reeba Hailston', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (53, 'Nathalia Sante', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (54, 'Kalil Posthill', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (55, 'Charmaine Dimeloe', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (56, 'Rafi Hawyes', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (57, 'Constantia Caddan', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (58, 'Cordula Worrell', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (59, 'Chandal Massen', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (60, 'Ade Proschek', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (61, 'Naoma Lelievre', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (62, 'Margaretha Stanlack', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (63, 'Barclay Liston', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (64, 'Robinson Mish', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (65, 'Batsheva Impett', 'Research and Development');
insert into funcionario (id_funcionario, nome, tipo) values (66, 'Katey Charge', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (67, 'Rozina Cage', 'Research and Development');
insert into funcionario (id_funcionario, nome, tipo) values (68, 'Lizette Cawkwell', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (69, 'Galvan Gertray', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (70, 'Kandace Dillintone', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (71, 'Vicky Koppel', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (72, 'Vinnie Flintoff', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (73, 'Dud Bennington', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (74, 'Alfy Slesser', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (75, 'Kerry Dawes', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (76, 'Dorolisa Steere', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (77, 'Frederick Asker', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (78, 'Lauren Manby', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (79, 'Wendell Postan', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (80, 'Janine Scuffham', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (81, 'Lorenzo Ell', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (82, 'Bogey Westwater', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (83, 'Bonnee Botten', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (84, 'Dyann Lamzed', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (85, 'Ware Cockshtt', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (86, 'Franciska Orlton', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (87, 'Lara Roblou', 'Research and Development');
insert into funcionario (id_funcionario, nome, tipo) values (88, 'Niall Abate', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (89, 'Brice Spittal', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (90, 'Ave Glynn', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (91, 'Nelly Spaunton', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (92, 'Gretna Compfort', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (93, 'Addy Veal', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (94, 'Bridgette Spikings', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (95, 'Verena Danev', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (96, 'Dion Mapholm', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (97, 'Maryjo Pinnington', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (98, 'Veronike Bowker', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (99, 'Valerye Purves', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (100, 'Chastity Cossington', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (101, 'Cahra Geipel', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (102, 'Nikolaos Sparhawk', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (103, 'Hertha Chimenti', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (104, 'Davis Tidd', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (105, 'Stanly Gouly', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (106, 'Kasper Stefanovic', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (107, 'Joceline Vidloc', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (108, 'Urbano Keymar', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (109, 'Gabe Deener', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (110, 'Glynnis Kopp', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (111, 'Jeanie Gristwood', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (112, 'Brandon Lockett', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (113, 'Callean Dickie', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (114, 'Joane Reddecliffe', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (115, 'Nolie Bellwood', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (116, 'Annmaria Bower', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (117, 'Ursuline Chesshire', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (118, 'Greggory Rockwill', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (119, 'Boote Pinshon', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (120, 'Trudie Landall', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (121, 'Ryann Penhall', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (122, 'Lanae Peepall', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (123, 'Nathan Aldin', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (124, 'Courtnay Kinworthy', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (125, 'Igor Skoggins', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (126, 'Duane Watt', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (127, 'Magdaia Renshall', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (128, 'Randi Priestnall', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (129, 'Erhart Wakeham', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (130, 'Danica Perrygo', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (131, 'Dorie Feather', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (132, 'Luce Mold', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (133, 'Heath Cribbins', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (134, 'Garrott Horney', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (135, 'Dita Epsly', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (136, 'Farlay Pettiward', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (137, 'Samaria Bucklee', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (138, 'Brenda Gaither', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (139, 'Valentijn Androletti', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (140, 'Demetria St. Leger', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (141, 'Arielle Frandsen', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (142, 'Shauna Bratt', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (143, 'Muire Caslake', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (144, 'Glad Burgess', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (145, 'Silvio Gatesman', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (146, 'Alfons Brigham', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (147, 'Johnathan Tottie', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (148, 'Rochester Kellitt', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (149, 'Quent Kewish', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (150, 'Lucho Bonsale', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (151, 'Brade Mc Giffin', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (152, 'Cammy Burman', 'Research and Development');
insert into funcionario (id_funcionario, nome, tipo) values (153, 'Beverlie Norvel', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (154, 'Wallis Cambden', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (155, 'Waldemar Maynard', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (156, 'Thorny Springle', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (157, 'Budd Bowyer', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (158, 'Pearce Blenkin', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (159, 'Adi Brimble', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (160, 'Lindie Clarridge', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (161, 'Simon Washbrook', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (162, 'Steffane Patley', 'Marketing');
insert into funcionario (id_funcionario, nome, tipo) values (163, 'Corrie Maccaddie', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (164, 'Shell Duckering', 'Human Resources');
insert into funcionario (id_funcionario, nome, tipo) values (165, 'Tamarah Rangle', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (166, 'Kendricks Wringe', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (167, 'Joel Kezor', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (168, 'Guy McVaugh', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (169, 'Jaine Raysdale', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (170, 'Ingrid Goodbourn', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (171, 'Bryn Gingle', 'Business Development');
insert into funcionario (id_funcionario, nome, tipo) values (172, 'Elna Tommen', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (173, 'Sterne Every', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (174, 'Matthias Furney', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (175, 'Mina Skellen', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (176, 'Valenka Passby', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (177, 'Miles Kainz', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (178, 'Vinson Johnes', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (179, 'Elizabeth Gigg', 'Research and Development');
insert into funcionario (id_funcionario, nome, tipo) values (180, 'Mommy Van der Veldt', 'Sales');
insert into funcionario (id_funcionario, nome, tipo) values (181, 'Grannie Godleman', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (182, 'Vernice Gready', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (183, 'Shellysheldon Haynesford', 'Accounting');
insert into funcionario (id_funcionario, nome, tipo) values (184, 'Ardys Cardenas', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (185, 'Laverna Suffe', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (186, 'Leupold O''Griffin', 'Engineering');
insert into funcionario (id_funcionario, nome, tipo) values (187, 'Demetri Latchmore', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (188, 'Carlota Doree', 'Training');
insert into funcionario (id_funcionario, nome, tipo) values (189, 'Catharina Marcam', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (190, 'Gordy Verman', 'Research and Development');
insert into funcionario (id_funcionario, nome, tipo) values (191, 'Ozzy Gimbart', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (192, 'Rustie Zucker', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (193, 'Adrien Caplan', 'Support');
insert into funcionario (id_funcionario, nome, tipo) values (194, 'Lilias McDirmid', 'Legal');
insert into funcionario (id_funcionario, nome, tipo) values (195, 'Nichols Masurel', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (196, 'Jade Davidy', 'Product Management');
insert into funcionario (id_funcionario, nome, tipo) values (197, 'Wilhelmine Furmagier', 'Services');
insert into funcionario (id_funcionario, nome, tipo) values (198, 'Cristobal Villa', 'Research and Development');
insert into funcionario (id_funcionario, nome, tipo) values (199, 'Correy Manger', 'Research and Development');
insert into funcionario (id_funcionario, nome, tipo) values (200, 'Maddie Foystone', 'Legal');
